// Mô phỏng chơi dài như người thật: nhập đủ hàng, bày quầy, thuê nhân viên, chế món hạng cao, tự pha (8–12 giây/ly), thi thanh tra (đạt 85%), mua đồ siêu hiếm.
const fs=require('fs'),vm=require('vm');const src=fs.readFileSync(process.argv[2],'utf8'),DAYS=+(process.argv[3]||300),SEED=+(process.argv[4]||1);
const stub=new Proxy(function(){},{get:(t,p)=>p===Symbol.toPrimitive?()=>0:p==='length'?0:p===Symbol.iterator?[][Symbol.iterator]:stub,apply:()=>stub,construct:()=>stub,set:()=>true});
const store={};let seed=SEED*9301+49297;const M=Object.create(Math);M.random=()=>{seed=(seed*9301+49297)%233280;return seed/233280};
const ctx={console,Math:M,JSON,Date,Object,Array,Set,Map,Promise,String,Number,Symbol,Proxy,Error,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{},requestAnimationFrame:()=>0,performance:{now:()=>0},devicePixelRatio:2,btoa:s=>s,atob:s=>s,unescape,escape,encodeURIComponent,decodeURIComponent,
 document:{querySelector:()=>stub,querySelectorAll:()=>[],createElement:()=>stub,body:stub,addEventListener:()=>{},hidden:false},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)}},Image:function(){return{}},navigator:stub,addEventListener:()=>{},fs};
ctx.window=ctx;ctx.DAYS=DAYS;vm.createContext(ctx);
vm.runInContext(src+`;toast=()=>{};const __T=[];setTimeout=(f,ms)=>{__T.push([now+(ms||0)/1000,f]);return 0};const __run=()=>{__T.sort((a,b)=>a[0]-b[0]);while(__T.length&&__T[0][0]<=now){const f=__T.shift()[1];try{f()}catch(e){}}};
(function(){S=migrate(fresh());const L=[],lv=[],P={pass:0,fail:0},A={};const log=(...a)=>L.push(a.join(' '));let bestDay=0;
 const best=(n)=>{const own=[...S.drinks,...S.syrups].filter(k=>!(BASES[k]&&BASES[k].free));let bestC=null,bv=-9;const rec=(st,arr)=>{if(arr.length===n){if(!arr.some(k=>BASES[k]))return;if(S.recipes.some(r=>sameSet([...r.bs,...(r.ss||[])],arr)))return;const ci=comboInfo(arr);if(ci.avg<=-1.5||ci.pairs.some(p=>p.s<=-3))return;const m=2.6+.35*ci.avg-.12*Math.max(0,n-3);if(m>bv){bv=m;bestC=[...arr]}return}for(let i=st;i<own.length;i++){arr.push(own[i]);rec(i+1,arr);arr.pop()}};rec(0,[]);return bestC&&{ids:bestC,m:bv}};
 const prep=()=>{prepDay();
  // thi thanh tra khi đủ điều kiện (đạt 85%)
  if(shopReady(S)&&!S.licDue&&S.examDay!==S.day&&examDish((S.shop||0)+1)&&ownMoney()>=upFee((S.shop||0)+1)){startExam();if(D&&D.exam){const ok_=Math.random()<.85;D.exam.end=ok_?'pass':'fail';D.exam.ok=ok_?D.exam.n:1;D.exam.why='hết giờ';examFinish();if(ok_){P.pass++;lv.push('ngày '+S.day+': lên cấp '+(S.shop+1)+' ('+SHOP[S.shop].n+'), tiền còn '+fk(S.money))}else P.fail++}}
  // thuê nhân viên: đủ chỗ thì thuê người nhanh tay nhất; cấp 3 có 1 phục vụ, cấp 4 trở lên thêm 1 bảo vệ
  while(S.staff.length<staffMax()&&S.cands.length&&ownMoney()>2e5*(1+S.staff.length)){const nb=S.staff.filter(s=>s.role==='barista').length,role=(S.shop>=2&&!S.staff.some(s=>s.role==='cashier'))?'cashier':(S.shop>=3&&!S.staff.some(s=>s.role==='guard'))?'guard':'barista';S.cands.sort((a,b)=>(b.spd+b.skill)-(a.spd+a.skill));const st=S.cands.shift();st.role=role;S.staff.push(st)}
  S.staff.forEach(s=>{if(s.mood<35&&ownMoney()>3e5){spend('nhanvien',50000);s.mood=Math.min(100,s.mood+25)}});
  // mở nguyên liệu mới mỗi ~6 ngày nếu dư tiền
  if(S.day%6===0){const cand=[...Object.keys(BASES),...Object.keys(SYRUPS)].filter(k=>!ITEM(k).free&&!ITEM(k).rare&&!ownList(k).includes(k)&&ITEM(k).rc&&ownMoney()>ITEM(k).rc*3);if(cand.length){const k=cand.sort((a,b)=>ITEM(a).rc-ITEM(b).rc)[0];spend('mokhoa',ITEM(k).rc);ownList(k).push(k);A.learn=(A.learn||0)+1}}
  // chế món mới (kiểm định nhanh) khi còn chỗ trên thực đơn hoặc chưa có món hạng A
  const needA=!activeMenu().some(r=>r.grade==='A');if((activeMenu().length<menuCap()||needA)&&ownMoney()>6e5){for(const n of [3,2]){const b=best(n);if(b&&b.m>=2.8){spend('kiemdinh',150000);const r={id:S.ruid++,name:'Món '+S.ruid,bs:b.ids.filter(k=>BASES[k]),ss:b.ids.filter(k=>SYRUPS[k]),ts:[],fs:[],status:'pending',ready:S.day+1,price:null,on:false,until:null};S.recipes.push(r);inspect(r);if(r.status==='ok'){r.price=recValue(r);A.newRec=(A.newRec||0)+1;A['grade'+r.grade]=(A['grade'+r.grade]||0)+1}break}}}
  // thực đơn: món đạt, ưu tiên hệ số cao, đủ số món theo cấp
  const ok=S.recipes.filter(r=>r.status==='ok').sort((a,b)=>recMult(b)-recMult(a));ok.forEach(r=>r.on=false);ok.slice(0,menuCap()).forEach(r=>{r.on=true;r.price=Math.max(r.price||0,recValue(r))});
  // đồ siêu hiếm: mua nếu dư gấp đôi, gắn vào món hạng A chưa có đồ
  if(S.mkt&&S.mkt.d===S.day&&(S.mkt.kind||'gem')==='gem'&&ownMoney()>=GEMS[S.mkt.k].c*2&&!(S.gems||[]).some(g=>g.k===S.mkt.k)){spend('sieuhiem',GEMS[S.mkt.k].c);S.gemId=(S.gemId||0)+1;S.gems.push({id:S.gemId,k:S.mkt.k});A.gems=(A.gems||0)+1}
  (S.gems||[]).forEach(g=>{if(!S.recipes.some(r=>r.gem===g.id&&gemOf(r))){const r=activeMenu().find(r=>r.grade==='A'&&!gemOf(r));if(r)r.gem=g.id}});
  // nới quầy khi dư tiền
  {const n=S.qrows||12,c=QROW_COST[n];if(n<QROWS_MAX&&c&&ownMoney()>c*3){spend('quay',c);S.qrows=n+2;S.grid.forEach(o=>o.r+=2);syncLayout()}}
  syncLayout();try{autoLay()}catch(e){}try{autoBuy()}catch(e){}};
 const R={};let tot={rev:0,profit:0,cust:0,served:0,left:0,lost:0,stars:0,sc:0,quests:0,qdone:0,len:0,waste:0};
 for(let d=0;d<DAYS;d++){if([8,30,60,120,200,280].includes(d))fs.writeFileSync('dumps/d'+d+'.json',JSON.stringify(S));prep();const m0=S.money;if(emergencyNeeded())startDay(true);else if(!activeMenu().length||!canOpenNormal()){A.closed=(A.closed||0)+1;S.day++;continue}else startDay();
  const Dr=D;D.evPlan=D.evPlan||[];let t=0,PT=0;cup=null;
  while(D&&t<2500){const dt=.05;now+=dt;t+=dt;__run();if(!D)break;tickDay(dt);if(!D)break;
   S.staff.forEach(x=>{if(x.w&&x.w.broken){x.brokeT=(x.brokeT||0)+dt;if(x.brokeT>1.5){x.brokeT=0;staffDrop(x.id)}}});
   if(!cup&&D.away<=now){const c=target();if(c){const it=c.items[c.cur];if(!missingOf(it).length){cup=newCup(it.size,null);cup.cid=c.id;cup.ix=c.cur;PT=now+8+Math.random()*4}}}
   else if(cup&&now>=PT){const c=D.queue.find(x=>x.id===cup.cid);if(c&&c.items[cup.ix]&&!c.items[cup.ix].done){const it=c.items[cup.ix];Object.assign(cup,{pours:it.bs.map(k=>({k,amt:TARGET/it.bs.length})),fill:TARGET,syrups:[...(it.ss||[])],tops:[...it.ts],foams:[...(it.fs||[])],sugar:it.sugar?SUGAR[it.sugar]:0,ice:it.ice?ICE[it.ice][1]:0,skin:it.sk||null,gem:Math.random()<.92?it.gem:null});const cp=cup;cup=null;serveCup(c,cp.ix,cp,null)}else cup=null}
   if(D&&D.pend.length){const p=D.pend[0];if(p.t0!=null){if(p.pick==null)pendPick(p,p.kind==='lost'?'tra':p.kind==='tam'?'yes':p.kind==='coin'?'sap':'q0')}else{const b={dataset:{dec:'yes'}};D.pend.shift();p.c.dec=false;settle(p.c,p.s,p.kind==='bargain'?p.offer:null,p.notes)}}
   if(D&&D.ev)resolveEvent(Math.random()<.5,true)}
  __T.length=0;if(D){A.stuck=(A.stuck||0)+1;D.queue=[];D.walk=[];D.pend=[];D.ev=null;cup=null;sealing=null;S.staff.forEach(s=>{s.w=null;s.job=null});endDay()}
  const st=Dr.stars,avg=st.length?st.reduce((a,b)=>a+b,0)/st.length:0,ql=(S.q&&S.q.list)||[];
  tot.rev+=Dr.rev;tot.cust+=Dr.total;tot.served+=Dr.served;tot.left+=Dr.left;tot.lost+=Dr.lateLost||0;tot.stars+=avg*st.length;tot.sc+=st.length;tot.quests+=ql.length;tot.qdone+=ql.filter(q=>q.done).length;tot.len+=t;
  const row=S.ledger[S.ledger.length-1];{const g=R[S.shop]||(R[S.shop]={n:0,rev:0,plan:0,tot:0,sv:0,lf:0,lost:0,len:0,wage:0,mood:0,profit:0});g.n++;g.rev+=Dr.rev;g.plan+=(Dr.plan||Dr.total);g.tot+=Dr.total;g.sv+=Dr.served;g.lf+=Dr.left;g.lost+=Dr.lateLost||0;g.len+=t;g.wage+=row?row.wages:0;g.mood+=S.staff.length?S.staff.reduce((a,x)=>a+x.mood,0)/S.staff.length:0;g.profit+=S.money-m0}
  if((d+1)%25===0||d<3)log('ngày '+(S.day-1)+' · cấp '+(S.shop+1)+' · NV '+S.staff.length+' · khách '+Dr.total+' (giao '+Dr.served+', bỏ '+Dr.left+', trễ mất '+(Dr.lateLost||0)+') · thu '+fk(Dr.rev)+' · lương '+fk(row?row.wages:0)+' · tiền '+fk(S.money)+' · ★'+avg.toFixed(2)+' · 5★ '+S.five+' · DT '+fk(lifeRev(S))+' · '+(t/60).toFixed(1)+'ph · món '+activeMenu().length+'/'+menuCap()+' · đồ '+(S.gems||[]).length);
 }
 console.log(L.join('\\n'));console.log('--- theo cấp (trung bình mỗi ngày):');for(const k in R){const g=R[k],n=g.n;console.log('cấp '+(+k+1)+': '+n+' ngày · khách dự kiến '+(g.plan/n).toFixed(0)+', vào '+(g.tot/n).toFixed(0)+', giao '+(g.sv/n).toFixed(0)+', bỏ về '+(g.lf/n).toFixed(1)+', mất vì 22h '+(g.lost/n).toFixed(0)+' · thu '+fk(g.rev/n)+' · lương '+fk(g.wage/n)+' · lãi (tiền tăng) '+fk(g.profit/n)+' · ngày '+(g.len/n/60).toFixed(1)+' phút · tinh thần NV '+(g.mood/n).toFixed(0))}console.log('--- lên cấp:');console.log(lv.join('\\n')||'(chưa)');
 console.log('--- tổng '+DAYS+' ngày: thi đạt '+P.pass+', trượt '+P.fail+' · khách TB '+(tot.cust/DAYS).toFixed(0)+', giao '+(100*tot.served/tot.cust).toFixed(0)+'%, bỏ về '+(100*tot.left/tot.cust).toFixed(1)+'%, mất vì 22h '+(100*tot.lost/(tot.cust+tot.lost)).toFixed(0)+'% · ★TB '+(tot.stars/tot.sc).toFixed(2)+' · nhiệm vụ xong '+tot.qdone+'/'+tot.quests+' · ngày TB '+(tot.len/DAYS/60).toFixed(1)+' phút · '+JSON.stringify(A));
 const sp={};S.ledger.slice(-30).forEach(e=>{for(const k in e.spent)sp[k]=(sp[k]||0)+e.spent[k]});console.log('--- chi 30 ngày cuối: '+Object.entries(sp).sort((a,b)=>b[1]-a[1]).map(([k,v])=>(CAT[k]||k)+' '+fk(v)).join(', '))})();`,ctx);
